name: CD
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - run: npm install

  deploy:
    runs-on: ubuntu-latest

    needs: install
    if: github.ref == 'refs/heads/master'
    steps:
      - run: npm run deploy
